# Generated by Django 6.1.1 on 2026-10-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckstop',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckstop',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
