# Generated by Django 6.1.1 on 2026-10-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_truckstop_lat_truckstop_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('key', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('state', 'key'), name='unique_place_state_key')],
            },
        ),
    ]
